spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
